version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          ENV_FILE: $ENV_FILE
      - image: mysql:8.0
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_ROOT_HOST: "127.0.0.1"
          MYSQL_DATABE: db
        command: --default-authentication-plugin=mysql_native_password
    working_directory: ~/coffee
    steps:
      - checkout
      - restore_cache:
          keys:
            - rails-{{ checksum "Gemfile.lock"}}-{{ checksum "yarn.lock"}}
      - run:
          name: bundleをインストール
          command: bundle check || bundle install --jobs=4
      - run:
          name: yarnを追加
          command: yarn install
      - save_cache:
          key: rails-{{ checksum "Gemfile.lock"}}-{{ checksum "yarn.lock"}}
          paths:
            - vendor/bundle
            - node_modules
      - run:
          name: webpackを追加
          command: bundle exec bin/webpack
      - run:
          name: Decode ENV file
          command: echo $ENV_FILE | base64 --decode > .env
      - run:
          name: rubocop
          command: bundle exec rubocop
      - run: mv ./config/database.yml.ci ./config/database.yml
      - run:
          name: データベースを作成
          command: bundle exec rails db:create || bundle exec rails db:migrate
      - run:
          name: rspec test
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"
            bundle exec rspec -profile 10\
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
